name: "web_app"
mode: "dev"
port: 8081
version: "v0.0.2"
start_time: "2024-03-05"
machine_id: 1

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

auth:
  jwt_expire: 8760